### PR TITLE
Fix "undefinex index type" when indexing

### LINKED ISSUE #138: BulkResponseAggregator Undefined index
### What did you do?
Attempted to bulk insert indexes.

### What did you expect to happen?
Indexes to be inserted.

### What actually happened?
An error occurred.

```
In BulkResponseAggregator.php line 47:
Undefined index: type  
```

### What versions of PHP, Lumen and this module are you using?
PHP: 7.2.23
Lumen: 5.8.13
Elasticsearch: 7.5.0

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

I was able to fix the error by replacing line 47 with the following two lines.
```php
$item = $item["index"];
$item = $item['_type'];
```

I've tried to force an error to see the response object, but I've been unable to in my short testing time.

With the error object, I can open a PR to fix any potential errors with that.

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #138

### CODE REVIEW

File: tests/Documents/Bulk/BulkResponseAggregatorTest.php [hunk 1]
```diff
@@ -52,17 +52,17 @@ public function testAddResponse()
...
                 [
-                    'type' => [
+                    'delete' => [
                         '_index' => 'foo',
                         '_type'  => 'bar',
                         '_id'    => 'baz',
                     ],
                 ],
-                // An item with an error, but no caused_by
+                // An create operation with an error, but no caused_by
```
Comment (hugovk) [inline tests/Documents/Bulk/BulkResponseAggregatorTest.php]:
```suggestion
                // A create operation with an error, but no caused_by
```

File: tests/Documents/Bulk/BulkResponseAggregatorTest.php [hunk 2]
```diff
@@ -52,17 +52,17 @@ public function testAddResponse()
                         ],
                     ],
                 ],
-                // An item without an error
+                // An delete operation without an error
```
Comment (hugovk) [inline tests/Documents/Bulk/BulkResponseAggregatorTest.php]:
```suggestion
                // A delete operation without an error
```

File: tests/Documents/Bulk/BulkResponseAggregatorTest.php (hunk 1 above)
Comment (Jalle19) [reply tests/Documents/Bulk/BulkResponseAggregatorTest.php]: Thanks!
