### PR TITLE
Re-index improvements

### LINKED ISSUE #112: Don't die if the tasks API is slow to respond during re-indexing
### What did you do?

Re-index an index with lots of heavy re-indexing operations

### What did you expect to happen?

Everything to go smoothyl

### What actually happened?

The do/while loop can trigger a 504 exception and abort the whole process (the re-indexing operation continues in the background though, but we'll never get to the alias swap stage) since it can take quite a few seconds sometimes to get task data while Elasticsearch is under heavy load.

We should ignore exceptions in this do/while loop

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #112

Changes proposed in this pull request:
 * Add a progress bar to display the re-indexing process
 * Don't die if the tasks API is slow to respond during re-indexing

### CODE REVIEW

File: src/Pipelines/Stages/ReIndexStage.php [hunk 1]
```diff
@@ -56,15 +59,48 @@ public function __invoke($payload)
...
+     */
+    protected function renderProgressBar(array $task): void
+    {
+        // Use a progress bar to indicate how far a long the re-indexing has come
+        $progressBar = null;
+
+        do {
+            $response = ['completed' => false];
+
+            // Ignore ServerErrorResponseException, re-indexing can make these requests time out
```
Comment (mathewrapid) [inline src/Pipelines/Stages/ReIndexStage.php]: Is there a risk for an endless loop?
Are there any other cases than time out to throw `ServerErrorResponseException` ?
What if the Elastic server goes down during the loop?

Comment (Jalle19) [reply src/Pipelines/Stages/ReIndexStage.php]: For this particular API endpoint there shouldn't be much that can trigger an exception except timeouts. If Elasticsearch completely dies it should eventually come back at some point and allow the loop to exit, so I think this is such an edge case that it's not worth handling.
